### ISSUE TITLE
Execution without elevated rights gives wrong output

### ISSUE THREAD

**Issue by Tibap** [OWNsecurity/fastir_artifacts#3]
When executed from a non-privilege console, the output is: 
```
usage: FASTIR~1.EXE [-h] [-i INCLUDE] [-e EXCLUDE]
                    [-d DIRECTORY [DIRECTORY ...]] [-l] [-m MAXSIZE]
                    [-o OUTPUT] [-s]
FASTIR~1.EXE: error: unrecognized arguments: .\fastir_artifacts.exe
```
Would be nice to get a nice error message saying that elevated rights are needed.

**Comment by gaelmuller** [comment]
Thank you for reporting this. Could you give us more details on how exactly you executed FastIR ? For example, why is the file called `FASTIR-1.EXE` ?

Currently, I cannot reproduce. Executing `fastir_artifacts.exe` on a Windows system from an unprivileged account should trigger an UAC prompt.

**Comment by Tibap** [comment]
Not sure how to explain the `FASTIR~1.EXE`, but to reproduce you need to open a powershell console with no admin privilege and run `.\fastir_artifacts.exe`.

**Comment by gregorygui** [comment]
After more than 3 years impossible to reproduce the behavior.
